import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import { signIn, signOut, useSession } from "next-auth/client";
import { useEffect } from "react";
import client from "../helper/sanity";

import { useSelector, useDispatch } from "react-redux";
import {
  decrement,
  increment,
  setLoadedState,
} from "../redux/slices/counterSlice";
import { loadState, saveState } from "../helper/localStorage";

export default function Home({ data }) {
  console.log(data);
  const count = useSelector((state) => state.counter.value);
  const dispatch = useDispatch();

  useEffect(() => {
    const local = loadState();
    dispatch(setLoadedState(local));
  }, []);
  useEffect(() => {
    saveState(count);
  }, [count]);

  const [session, loading] = useSession();

  return (
    <div className={`${styles.container} container`}>
      <Head>
        <title>Ecom</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>{count}</div>
        <button onClick={() => dispatch(increment())}>+</button>
        <button onClick={() => dispatch(decrement())}>-</button>

        <h1 className={styles.title}>morbi interdum</h1>

        {!session && (
          <>
            Not signed in <br />
            <button className="btn btn--2" onClick={() => signIn()}>Sign In</button>
          </>
        )}
        {session && (
          <>
            Signed in as {session.user.email} <br />
            <button onClick={() => signOut()}>Sign out</button>
          </>
        )}
      </main>
    </div>
  );
}

// Create a query called homepageQuery
const homepageQuery = `*[_type == "product"]`;

export async function getStaticProps() {
  const homepageData = await client.fetch(homepageQuery);

  const data = { homepageData };

  return {
    props: {
      data,
    },
    revalidate: 1,
  };
}
